### ISSUE TITLE
Wordpress template from cloudmos

### ISSUE THREAD

**Issue by JGuibone** [akash-network/awesome-akash#381]
Good day i would like to report a possible issue with the wordpress template deployment from cloudmos..

after multiple attempts i finally got all green on the status of all the services im trying to implement using said template.
https://imgur.com/HGxEQLN

then after waiting for a couple of minutes and also checking the logs to make sure that their are no failed or error attempts.

i try'd entering the URI given by the provider.
and got this error message
https://imgur.com/3gB5G4p

i havnt change the template SDL too much only the password, unit and size. ports stayed the same.

`version: "3.1"

services:
  db:
    image: mariadb:10.6.13
    volumes:
      - "db-data:/var/lib/mysql"
    env:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      ####Replace password###
      - MYSQL_PASSWORD=testpass4you
    expose:
      - port: 3306
        to:
          - service: wordpress
    params:
      storage:
        sqldata:
          mount: /var/lib/mysql
  wordpress:
    image: trafex/wordpress:6.1.1
    depends_on:
    - db
    volumes:
      - "site-data:/var/www"
    env:
      - DB_HOST=db
      - DB_PASSWORD=wordpass
      - DB_NAME=wordpress
      - DB_USER=wordpress
      # - WORDPRESS_SITE_URL=example.com
      - FS_METHOD=direct
      - WP_REDIS_HOST=redis
    expose:
      - port: 80
        http_options:
          max_body_size: 104857600
        # accept: 
        # - "example.com"
        to:
          - global: true
    params:
      storage:
        data:
          mount: /var/www
  redis:
    image: bitnami/redis:latest
    expose:
      - port: 6379
        proto: tcp
        to:
          - service: wordpress
    env:
      - ALLOW_EMPTY_PASSWORD=yes
      ## Set if ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=testpassNum2
profiles:
  compute:
    wordpress:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 2Gi
        storage:
          - size: 2Gi
          - name: data
            size: 2Gi
            attributes:
              persistent: true
              class: beta3
    db:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 1Gi
        storage:
          - size: 1Gi
          - name: sqldata
            size: 1Gi
            attributes:
              persistent: true
              class: beta3
    redis:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          size: 1Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        wordpress:
          denom: uakt
          amount: 100000
        db:
          denom: uakt
          amount: 100000
        redis:
          denom: uakt
          amount: 100000

deployment:
  wordpress:
    akash:
      profile: wordpress
      count: 1
  db:
    akash:
      profile: db
      count: 1
  redis:
    akash:
      profile: redis
      count: 1`

given it has only been a couple of hours since my writing that ive deployed this so hopefully it fixes it self but could someone check if they are getting the same problem?

**Comment by 88plug** [comment]
This should be using the official Wordpress docker image. I will update shortly...

**Comment by 88plug** [comment]
This will get you moving again...

```
---
version: '2.0'
services:
  wordpress:
    image: wordpress
    depends_on:
    - db
    expose:
      - port: 80
        http_options:
          max_body_size: 104857600
        # accept: 
        # - "example.com"
        to:
          - global: true
    env:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=testpass4you
      - WORDPRESS_DB_NAME=wordpress
    params:
      storage:
        wordpress-data:
          mount: /var/www/html
          readOnly: false
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    expose:
      - port: 3306
        to:
          - service: wordpress
      - port: 33060
        to:
          - service: wordpress
    env:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=testpass4you
    params:
      storage:
        wordpress-db:
          mount: /var/lib/mysql
          readOnly: false
profiles:
  compute:
    wordpress:
      resources:
        cpu:
          units: 4
        memory:
          size: 4Gi
        storage:
          - size: 4Gi
          - name: wordpress-data
            size: 32Gi
            attributes:
              persistent: true
              class: beta3
    db:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          - size: 1Gi
          - name: wordpress-db
            size: 8Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    akash:
      #######################################################
      #Keep this section to deploy on trusted providers
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      #######################################################
      #Remove this section to deploy on untrusted providers
      #Beware* You may have deployment, security, or other issues on untrusted providers
      #https://docs.akash.network/providers/akash-audited-attributes
      pricing:
        wordpress:
          denom: uakt
          amount: 10000
        db:
          denom: uakt
          amount: 10000
deployment:
  wordpress:
    akash:
      profile: wordpress
      count: 1
  db:
    akash:
      profile: db
      count: 1
```
