### ISSUE TITLE
bare ssh image doesn't handle child processes 

### ISSUE THREAD

**Issue by andy108369** [akash-network/awesome-akash#565]
bare ssh [image](https://github.com/akash-network/awesome-akash/pull/536) doesn't handle child processes;
https://akash.network/docs/providers/provider-faq-and-guide/#kill-zombie-processes kills such container when they unintentionally spawn Z-ombie (defunct) processes.

We should `exec /usr/sbin/sshd -D` instead of `exec tail -f /dev/null` to fix it.

Good ssh container example is [here](https://github.com/akash-network/support/issues/87#issuecomment-1759421892)

## Zombie process reproducer

Thanks Deval for the reprocuder

### step 1

```
---
version: "2.0"
services:
  deployment-rit-test:
    image: ghcr.io/akash-network/ubuntu-2404-ssh:1
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
    env:
      - >-
        SSH_PUBKEY=[SSH_PUBKEY]
    params:
      storage:
        data:
          mount: /mnt/blabs
          readOnly: false
profiles:
  compute:
    deployment-rit-test:
      resources:
        cpu:
          units: 32
        memory:
          size: 64GB
        storage:
          - size: 128GB
          - name: data
            size: 256GB
            attributes:
              persistent: true
              class: beta3
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx4090
  placement:
    dcloud:
      pricing:
        deployment-rit-test:
          denom: uakt
          amount: 10000
deployment:
  deployment-rit-test:
    dcloud:
      profile: deployment-rit-test
      count: 1
```

### step 2
```
apt-get update
apt-get upgrade -y
apt-get install -y git nano wget curl build-essential

wget https://repo.anaconda.com/archive/Anaconda3-2024.06-1-Linux-x86_64.sh
chmod +x ./Anaconda3-2024.06-1-Linux-x86_64.sh
./Anaconda3-2024.06-1-Linux-x86_64.sh
(I installed the anaconda3 at /mnt/blabs/anaconda3)
export PATH=$PATH:/mnt/blabs/anaconda3/bin # or set at .bashrc

conda init

cd /mnt/blabs
git clone https://github.com/apple/ml-ferret
cd ml-ferret

conda create -n ferret python=3.10 -y
conda activate ferret
pip install --upgrade pip
pip install -e . # this is the break point if the kill_zombie script is runing.
```

zombie process:
![image](https://github.com/user-attachments/assets/a1404a08-aab2-4c1b-ae95-fb68ea8605a5)
