### ISSUE TITLE
Quai-gpu-miner fails with No usable mining devices found

### ISSUE THREAD

**Issue by bobwith2bees** [akash-network/awesome-akash#633]
I am unable to deploy an instance using nvidia rtx3090 using the latest Quai-gpu-miner.

Reverting the quai-gpu-miner-run docker image (see the commit) resolves the issue.

 https://github.com/akash-network/awesome-akash/commit/6a2827a2245ce51fe61ec1ac4457d44453854ace

But I think with Quai mainnet miners need to be running the v0.5.0 quai-gpu-miner-run image.  

Symptom with the current template - console log of instance fails CUDA test on RTX 3090
```
Log:
[quai]: 
[quai]: 
[quai]: quai-gpu-miner 1.2.4+commit.0e7d056b
[quai]: Build: linux/release/gnu
[quai]: 
[quai]: CUDA Error : forward compatibility was attempted on non supported HW
[quai]: Error: No usable mining devices found
[quai]: 
```

SDL yaml hardware:
```
  compute:
    quai-miner:
      resources:
        cpu:
          units: 1
        memory:
          size: 8Gb
        storage:
          - size: 1Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx3090
                  ram: 24Gi
                  interface: pcie
```

***Workaround:***
* Manually edit the yaml to revert the miner docker image from v0.5.0 to v0.3.0.  NOTE:  It's not clear if it will mine a block given QUAI launched their main net this week.
```
  quai-miner:
    image: quainetwork/quai-gpu-miner-run:v0.3.0
```
